<font size=5>
Создать ноутбук, в котором будут приведены собственные примеры на языке Python для каждого из представленных свойств матричных вычислений.
</font>

In [1]:
import numpy as np

#### Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [2]:
A = np.random.randint(-20, 100, (3, 3))
print(A)
print("Транспонированная матрица: ")
print(A.T)
print("Дважды транспонированная матрица: ")
R = (A.T).T
print(R)

[[-12  56  82]
 [ 92  56  25]
 [ -3  23   8]]
Транспонированная матрица: 
[[-12  92  -3]
 [ 56  56  23]
 [ 82  25   8]]
Дважды транспонированная матрица: 
[[-12  56  82]
 [ 92  56  25]
 [ -3  23   8]]


#### Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [3]:
A = np.random.randint(-20, 100, (3, 3))
B = np.random.randint(-20, 100, (3, 3))
print(f"A\n{A},\nB\n{B}")

print("Транспонирование суммы матриц:")
L = (A + B).T
print(L)

print("Сумма транспонированных матриц:")
R = A.T + B.T
print(R)

A
[[ 87  33   8]
 [ 22  33  76]
 [ 89 -19  27]],
B
[[77  5 85]
 [ 1 52 83]
 [69 49 49]]
Транспонирование суммы матриц:
[[164  23 158]
 [ 38  85  30]
 [ 93 159  76]]
Сумма транспонированных матриц:
[[164  23 158]
 [ 38  85  30]
 [ 93 159  76]]


#### Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке

In [4]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
print(f"A\n{A},\nB\n{B}")

print("Транспонирование произведения матриц:")
L = (A.dot(B)).T
print(L)

print("Произведение транспонированных матриц:")
R = (B.T).dot(A.T)
print(R)

A
[[3 2 3]
 [1 3 9]
 [5 6 7]],
B
[[5 0 6]
 [0 8 7]
 [5 9 1]]
Транспонирование произведения матриц:
[[ 30  50  60]
 [ 43 105 111]
 [ 35  36  79]]
Произведение транспонированных матриц:
[[ 30  50  60]
 [ 43 105 111]
 [ 35  36  79]]


#### Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [5]:
A = np.random.randint(0, 20, (3, 3))
print(A)
k = 3

print(f"Транспонирование произведения матрицы на число {k}:")
L = (k * A).T
print(L)

print(f"Произведение числа {k} на транспонированную матрицу:")
R = k * (A.T)
print(R)

[[11 11 17]
 [13  3 11]
 [ 6  6 12]]
Транспонирование произведения матрицы на число 3:
[[33 39 18]
 [33  9 18]
 [51 33 36]]
Произведение числа 3 на транспонированную матрицу:
[[33 39 18]
 [33  9 18]
 [51 33 36]]


#### Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [6]:
A = np.random.randint(0, 10, (3, 3))
print(A)

print("Определитель исходной матрицы:")
A_det = np.linalg.det(A)
print(format(A_det, '.9g'))

print("Определитель транспонированной матрицы:")
A_T_det = np.linalg.det(A.T)
print(format(A_T_det, '.9g'))

[[2 2 2]
 [6 8 1]
 [0 4 5]]
Определитель исходной матрицы:
60
Определитель транспонированной матрицы:
60


## <b> Действия над матрицами </b>

### Умножение матриц на число

#### Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [7]:
A = np.random.randint(0, 10, (2, 2))
print(A)

print("Произведение единицы и матрицы:")
L = 1 * A
print(L)

[[5 6]
 [8 5]]
Произведение единицы и матрицы:
[[5 6]
 [8 5]]


#### Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [8]:
A = np.random.randint(-20, 100, (2, 2))
Z = np.matrix('0 0; 0 0')
L = 0 * A
print("Нулевая матрица:")
print(Z)
print("Произведение матрицы на 0:")
print(L)

Нулевая матрица:
[[0 0]
 [0 0]]
Произведение матрицы на 0:
[[0 0]
 [0 0]]


#### Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [9]:
A = np.random.randint(0, 20, (3, 3))
print(A)
p = 2
q = 3
print("Произведение матрицы на сумму чисел:")
L = (p + q) * A
print(L)
print("Произведений матрицы на каждое из этих чисел:")
R = p * A + q * A
print(R)

[[ 6 17  3]
 [ 9 17  2]
 [10  2 10]]
Произведение матрицы на сумму чисел:
[[30 85 15]
 [45 85 10]
 [50 10 50]]
Произведений матрицы на каждое из этих чисел:
[[30 85 15]
 [45 85 10]
 [50 10 50]]


#### Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [10]:
A = np.random.randint(0, 10, (3, 3))
print(A)
p = 2
q = 3
print("Произведение матрицы на произведение чисел:")
L = (p * q) * A
print(L)
print("Произведение второго числа и заданной матрицы, умноженное на первое число:")
R = p * (q * A)
print(R)

[[8 9 3]
 [2 7 0]
 [4 8 0]]
Произведение матрицы на произведение чисел:
[[48 54 18]
 [12 42  0]
 [24 48  0]]
Произведение второго числа и заданной матрицы, умноженное на первое число:
[[48 54 18]
 [12 42  0]
 [24 48  0]]


#### Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [11]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
print(f"A\n{A} \nB\n{B}")
k = 3
print("Произведение суммы матриц на число:")
L = k * (A + B)
print(L)
print("Cуммa произведений этих матриц на заданное число:")
R = k * A + k * B
print(R)

A
[[4 9 8]
 [0 4 0]
 [7 8 3]] 
B
[[2 3 6]
 [4 7 8]
 [5 4 0]]
Произведение суммы матриц на число:
[[18 36 42]
 [12 33 24]
 [36 36  9]]
Cуммa произведений этих матриц на заданное число:
[[18 36 42]
 [12 33 24]
 [36 36  9]]


### Сложение матриц

#### Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [12]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
print(f"A\n{A} \nB\n{B}")

print("A + B")
L = A + B
print(L)
print("B + A")
R = B + A
print(R)

A
[[5 6 8]
 [8 4 1]
 [6 5 6]] 
B
[[8 8 0]
 [0 5 2]
 [2 7 8]]
A + B
[[13 14  8]
 [ 8  9  3]
 [ 8 12 14]]
B + A
[[13 14  8]
 [ 8  9  3]
 [ 8 12 14]]


#### Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [13]:
A = np.random.randint(0, 20, (2, 2))
B = np.random.randint(0, 20, (2, 2))
C = np.random.randint(0, 20, (2, 2))
print(f"A\n{A} \nB\n{B} \nC\n{C}")

print("A + (B + C)")
L = A + (B + C)
print(L)
print("(A + B) + C")
R = (A + B) + C
print(R)

A
[[13 17]
 [15  6]] 
B
[[ 3  9]
 [19 19]] 
C
[[16 17]
 [ 2  9]]
A + (B + C)
[[32 43]
 [36 34]]
(A + B) + C
[[32 43]
 [36 34]]


#### Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [14]:
A = np.random.randint(0, 20, (2, 2))
print(f"A \n{A}")
print(f"-A \n{A * (-1)}")

print(f"Сумма:")
L = A + (-1)*A
print(L)

A 
[[19 19]
 [ 7 16]]
-A 
[[-19 -19]
 [ -7 -16]]
Сумма:
[[0 0]
 [0 0]]


### Умножение матриц

#### Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [15]:
A = np.random.randint(0, 10, (2, 2))
B = np.random.randint(0, 10, (2, 2))
C = np.random.randint(0, 10, (2, 2))
print(f"A \n{A},\nB \n{B},\nC \n{C}")

print("A*(B*C)")
L = A.dot(B.dot(C))
print(L)
print("(A*B)*C")
R = (A.dot(B)).dot(C)
print(R)

A 
[[8 7]
 [8 6]],
B 
[[5 1]
 [8 8]],
C 
[[1 6]
 [9 8]]
A*(B*C)
[[ 672 1088]
 [ 592  976]]
(A*B)*C
[[ 672 1088]
 [ 592  976]]


#### Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [16]:
A = np.random.randint(0, 10, (2, 2))
B = np.random.randint(0, 10, (2, 2))
C = np.random.randint(0, 10, (2, 2))
print(f"A \n{A},\nB \n{B},\nC \n{C}")

print("A*(B+C)")
L = A.dot(B + C)
print(L)
print("(A*B + A*C)")
R = A.dot(B) + A.dot(C)
print(R)

A 
[[7 3]
 [9 4]],
B 
[[1 7]
 [1 6]],
C 
[[4 9]
 [7 1]]
A*(B+C)
[[ 59 133]
 [ 77 172]]
(A*B + A*C)
[[ 59 133]
 [ 77 172]]


#### Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [17]:
A = np.random.randint(0, 10, (2, 2))
B = np.random.randint(0, 10, (2, 2))
print(f"A\n{A} \nB\n{B}")

print("A*B")
L = A.dot(B)
print(L)
print("B*A")
R = B.dot(A)
print(R)

A
[[0 4]
 [3 5]] 
B
[[0 7]
 [2 7]]
A*B
[[ 8 28]
 [10 56]]
B*A
[[21 35]
 [21 43]]


#### Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [18]:
A = np.random.randint(0, 10, (3, 3))
E = np.eye(3)
print(f"A \n{A}")

print("E*A")
L = E.dot(A)
print(L)
print("A*E")
R = A.dot(E)
print(R)

A 
[[1 5 1]
 [2 4 7]
 [3 7 0]]
E*A
[[1. 5. 1.]
 [2. 4. 7.]
 [3. 7. 0.]]
A*E
[[1. 5. 1.]
 [2. 4. 7.]
 [3. 7. 0.]]


#### Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [19]:
A = np.random.randint(0, 10, (3, 3))
Z = np.zeros((3, 3))
print(f"A \n{A}")

print("Z*A")
L = Z.dot(A)
print(L)
print("A*Z")
R = A.dot(Z)
print(R)

A 
[[9 6 9]
 [4 2 2]
 [7 6 3]]
Z*A
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
A*Z
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Определитель матрицы

#### Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [20]:
A = np.random.randint(0, 10, (3, 3))
print(f"A \n{A}")

det_A = round(np.linalg.det(A), 3)
print(f"△A = {det_A}")

print(f"A(T) \n{A.T}")
det_A_t = round(np.linalg.det(A.T), 3)
print(f"△A(T) = {det_A_t}")

A 
[[7 3 5]
 [2 3 2]
 [8 4 7]]
△A = 17.0
A(T) 
[[7 2 8]
 [3 3 4]
 [5 2 7]]
△A(T) = 17.0


#### Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [21]:
A = np.random.randint(0, 10, (3, 3))
print(f"A \n{A}")
det_A = np.linalg.det(A)
print(f"△A = {det_A}")

A = np.matrix('0 5 2; 0 6 2; 0 9 4')
print(f"A \n{A}")
det_A = np.linalg.det(A)
print(f"△A = {det_A}")

A 
[[2 7 1]
 [0 9 7]
 [9 9 7]]
△A = 360.00000000000006
A 
[[0 5 2]
 [0 6 2]
 [0 9 4]]
△A = 0.0


#### Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [22]:
A = np.matrix('2 6 3; 5 2 8; 1 2 3')
print(f"A \n{A}")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}")

B = np.matrix('2 6 3; 1 2 3; 5 2 8')
print(f"B \n{B}")
det_B = round(np.linalg.det(B), 3)
print(f"△B = {det_B}")

A 
[[2 6 3]
 [5 2 8]
 [1 2 3]]
|A| = -38.0
B 
[[2 6 3]
 [1 2 3]
 [5 2 8]]
△B = 38.0


#### Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [23]:
A = np.matrix('2 6 3; 5 2 8; 1 2 3')
print(f"A \n{A}")
det_A = round(np.linalg.det(A), 3)
print(f"△A = {det_A}")

A = np.matrix('2 6 3; 1 2 3; 1 2 3')
print(f"A \n{A}")
det_A = round(np.linalg.det(A), 3)
print(f"△A = {det_A}\n")

A 
[[2 6 3]
 [5 2 8]
 [1 2 3]]
△A = -38.0
A 
[[2 6 3]
 [1 2 3]
 [1 2 3]]
△A = 0.0



#### Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [24]:
A = np.random.randint(-15, 90, (3, 3))
print(f"A \n{A}")
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(f"B \n{B}")
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print(f"△A * k = {det_A * k}")
print(f"△B = {det_B}")

A 
[[-8 53 66]
 [ 4 16 17]
 [-7 31 28]]
B 
[[ -8  53  66]
 [  4  16  17]
 [-14  62  56]]
△A * k = 7930.0
△B = 7930.0


#### Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [25]:
A = np.matrix('7 4 3; 7 4 3; 2 7 1')
B = np.matrix('7 4 3; 1 8 -4; 2 7 1')
C = A.copy()
C[1, :] += B[1, :]
print(f"C \n{C}")
print(f"A \n{A}")
print(f"B \n{B}")

print("△C")
print(round(np.linalg.det(C), 3))
print("△A + △B")
print(round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3))

C 
[[ 7  4  3]
 [ 8 12 -1]
 [ 2  7  1]]
A 
[[7 4 3]
 [7 4 3]
 [2 7 1]]
B 
[[ 7  4  3]
 [ 1  8 -4]
 [ 2  7  1]]
△C
189.0
△A + △B
189.0


#### Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [26]:
A = np.random.randint(1, 10, (3, 3))
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(f"A\n{A} \nB\n{B}")


print("△A")
print(round(np.linalg.det(A), 3))
print("△B")
print(round(np.linalg.det(B), 3))

A
[[8 3 7]
 [5 7 7]
 [7 8 4]] 
B
[[ 8  3  7]
 [21 13 21]
 [ 7  8  4]]
△A
-200.0
△B
-200.0


#### Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [27]:
A = np.matrix('6 2 4; 2 1 9; 4 3 2')
print(f"A \n{A}")
k = 2

A[1, :] = A[0, :] + k * A[2, :]
print("△A")
print(round(np.linalg.det(A), 3))

A 
[[6 2 4]
 [2 1 9]
 [4 3 2]]
△A
0.0


#### Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [28]:
A = np.matrix('6 2 4; 2 1 9; 4 3 2')
print(f"A \n{A}")
print(round(np.linalg.det(A), 3))

k = 4
A[1, :] = k * A[0, :]
print(A)
print("△A")
print(round(np.linalg.det(A), 3))

A 
[[6 2 4]
 [2 1 9]
 [4 3 2]]
-78.0
[[ 6  2  4]
 [24  8 16]
 [ 4  3  2]]
△A
0.0


### Обратная матрица

#### Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [29]:
A = np.random.uniform(0, 10, (2, 2))
print(A)
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A_inv_inv)

[[0.67122576 5.44947895]
 [9.83382116 5.56579284]]
[[0.67122576 5.44947895]
 [9.83382116 5.56579284]]


#### Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [30]:
A = np.random.uniform(0, 10, (2, 2))
print("Обратная матрица транспонированной матрицы:")
L = np.linalg.inv(A.T)
print(L)

print("Транспонированная матрица от обратной матрицы:")
R = (np.linalg.inv(A)).T
print(R)

Обратная матрица транспонированной матрицы:
[[ 0.34985134 -0.25989548]
 [-0.20497718  0.32384085]]
Транспонированная матрица от обратной матрицы:
[[ 0.34985134 -0.25989548]
 [-0.20497718  0.32384085]]


#### Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [31]:
A = np.random.uniform(0, 10, (2, 2))
B = np.random.uniform(0, 10, (2, 2))

print("Обратная матрица произведения матриц:")
L = np.linalg.inv(A.dot(B))
print(L)

print("Произведение обратных матриц:")
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(R)

Обратная матрица произведения матриц:
[[ 0.06213741 -0.02910627]
 [-0.08959203  0.06849657]]
Произведение обратных матриц:
[[ 0.06213741 -0.02910627]
 [-0.08959203  0.06849657]]
